### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Zonimi** [Doregon/Inspiron-5570-KBR-Hackintosh#1]
Hello, first I would like to thank you for making EFI available for i7-8550U, thank you very much!

However, I'm having a problem with the installation, problem: https://imgur.com/1IXmzbz

Could you help me? paid if necessary.

telegram: @Zonimi
discord: Zonimi#6606

**Comment by Doregon** [comment]
Can you pass along your specs?

**Comment by Zonimi** [comment]
> Can you pass along your specs?
It is a Dell Inspiron 5570 with i7-8550U

**Comment by Doregon** [comment]
What's your GPU? I noticed that you have a boot argument for WhateverGreen, and usually the "MACH Reboot" hang is caused by a problem with your GPU setup.

**Comment by Zonimi** [comment]
> What's your GPU? I noticed that you have a boot argument for WhateverGreen, and usually the "MACH Reboot" hang is caused by a problem with your GPU setup.

It has a UHD 620 and AMD 530, I tried to install it from an image from the "Olarila" forum I don't have a real mac to create a clean image

**Comment by Doregon** [comment]
Go to my quick-hackintosh-guides repo to find out how to make a good installer without having to use others. I'll start looking into frame buffer stuff to make your dGPU stuff work.

**Comment by Zonimi** [comment]
> Go to my quick-hackintosh-guides repo to find out how to make a good installer without having to use others. I'll start looking into frame buffer stuff to make your dGPU stuff work.

I managed to adapt some things for Windows, but I'm having a problem in the last step with the command _sudo dmg2img -p Y -i BaseSystem.dmg -o /dev /sdX2_ problem is in the path /dev/... in Windows the _lsblk_ command is displayed as follows: https://imgur.com/Ag8DCLq

Do you know how I can be selecting the pendrive on the command line ?, I've tried the drive letter, but it didn't work

**Comment by Doregon** [comment]
Oh shoot, I forgot that I didn't have a Windows guide yet! Sorry, go to the MS Store and download Ubuntu from there, you should be able to run Linux commands directly. I need a couple days to get the Windows guide ready, sorry about that!

**Comment by Zonimi** [comment]
> Oh shoot, I forgot that I didn't have a Windows guide yet! Sorry, go to the MS Store and download Ubuntu from there, you should be able to run Linux commands directly. I need a couple days to get the Windows guide ready, sorry about that! To clone the repo, you can use the command.`git`

I did as you instructed, but the pendrive is not listed in the `lsblk` command, I also tried `fdisk -l` but it didn't work

**Comment by Doregon** [comment]
Okay, so there's two options, then. 

Either, you make a bootable Linux USB and install it somewhere on your PC to make the USB for Big Sur, or you use Windows and gibMacOS but risk some hardware not working because of how you can't make a Big Sur USB on Windows.

**Comment by Doregon** [comment]
> edit: Looking for more, I managed to extract the image to the pendrive

Does that mean you've successfully gotten the USB made?

**Comment by Zonimi** [comment]
> > edit: Looking for more, I managed to extract the image to the pendrive
> 
> Does that mean you've successfully gotten the USB made?

Using Windows resources, I managed to extract the image in .iso, is that correct?

**Comment by Doregon** [comment]
use balenaetcher and try to flash the new iso file to your usb

**Comment by Zonimi** [comment]
> use balenaetcher and try to flash the new iso file to your usb

In belenaEtcher shows the following message: https://imgur.com/n1gRaUj

**Comment by Doregon** [comment]
ok, well... I guess you have two options from here:

get virtualbox, install linux and run the commands directly in there so you don't need to change anything to get macOS installed is the first. I'd honestly recommend this over the second option...

...which is download macOS Catalina using gibMacOS (the only file you need is RecoveryDMGMeta.pkg) and then use the MakeInstall file to flash it. This would be harder because you'll have to swap out kexts.

**Comment by Zonimi** [comment]
I tried the first option, but it was a problem to recognize the USB Flash Drive too, I think I would wait for your guide for Windows that you mentioned, to avoid any future problems, thanks

I also thank you for the time I took you (Forgive my English.)

**Comment by Zonimi** [comment]
Hi, I followed your guide and everything was fine, can I use the EFI of this repository for pre-installation?

Apparently it's the same model, Dell Inspirion 5570 with i7-8550U and UHD 620 / AMD 530

**Comment by Doregon** [comment]
If you followed the guide and downloaded the Catalina image, you'll need to replace the AirportItlwm.kext with one made for Catalina (the Big Sur version won't work on Cat, and obviously you can find it in the OpenIntelWireless repositories.)

**Comment by Zonimi** [comment]
I made the change to the kext but without success, when booting the USB it goes to the Windows recovery screen/Dell SupportAssist

Changes I made to the BIOS:
SATA: AHCI
VT/d: disabled

**Comment by Doregon** [comment]
Disable Secure Boot, PTT, Wake on USB, and Legacy Option ROMs

**Comment by Zonimi** [comment]
The same error still persists, led me to Windows recovery 🤔

**Comment by Doregon** [comment]
Try manually putting the \EFI\BOOT\BOOTx64.EFI entry into the BIOS (go to Boot Sequence > Add New, then check for your USB and double click)

**Comment by Doregon** [comment]
Did it work?

**Comment by Zonimi** [comment]
Still not working, I tried to boot with the EFI generated by gibMacOS (without a config.plist) and got to boot the OC but obviously I had the error due to the lack of config (https://imgur.com/bYQTX77), I tried with the EFI of your repository and went to the recovery screen

Is the problem with EFI now? 🤔

**Comment by Doregon** [comment]
Hmm. My friend and I were able to boot from this EFI and we can still boot from it, and we got the SupportRecovery screen when our BIOS wasn't configured for OC correctly. I'm making another guide (one that works for Big Sur) so hang tight as I continue to work on this problem.

**Comment by Zonimi** [comment]
Hello, I followed the steps of the new guide using virtualbox, now I continue using the Linux guide(linux-10.7-to-11) or wait for the rest of the guide?

**Comment by Zonimi** [comment]
Your guides are very good, I will recommend in the hackintosh groups that I participate in my country, thanks for that.

I followed the linux gui in the virtualbox, everything went well, I believe the problem is in EFI, I don't understand anything about the EFI creation process, maybe the best thing for me is to give up the hackintosh 🙃

**Comment by Doregon** [comment]
I'll start working on an EFI creation guide, making things simple from Dortania's guide. Wait, hang on, can you show me how the EFI folder is set up?

**Comment by Zonimi** [comment]
The structure I believe is correct, https://imgur.com/nQQWZSY, I tried to use the EFI generic for intel kaby lake from the forum "Olarila" but without success, it even started to crash at a certain point, I will run it again and send it a photo

**Comment by Doregon** [comment]
Try running mine without any modifications and see if it boots. The Kaby Lake Refresh CPUs we have need the Coffee Lake SSDTs, Kaby Lake patches. Everything should work without any modifications to my EFI (the AMD GPU may or may not)

**Comment by Zonimi** [comment]
> Try running mine without any modifications and see if it boots. The Kaby Lake Refresh CPUs we have need the Coffee Lake SSDTs, Kaby Lake patches. Everything should work without any modifications to my EFI (the AMD GPU may or may not)

With your EFI I get a recovery screen for some reason

Using a generic EFI I crash at this point: https://imgur.com/TJ2KhdQ
EFI folder: https://tinyurl.com/yxjpwbhg

**Comment by Zonimi** [comment]
I tested another EFI for my model and got to the Apple logo and crashed on a gray screen

**Comment by Doregon** [comment]
Hmm, could you send me your service tag so I can look your model up on the Dell site?

**Comment by Zonimi** [comment]
> Hmm, could you send me your service tag so I can look your model up on the Dell site?

8NM33T2

**Comment by Doregon** [comment]
Try disabling the ApplePS2SmartTouchpad.kext file in the config?

**Comment by Zonimi** [comment]
Is there a program to edit the config.plis through windows?

**Comment by Doregon** [comment]
Yeah, look for ProperTree (it's on GitHub)

**Comment by Doregon** [comment]
Is there a GPU initialization problem? Add `-wegnoegpu` to the boot arguments for Olarila's config.plist.

**Comment by Zonimi** [comment]
You already have this argument: https://imgur.com/GaHScZX

**Comment by Doregon** [comment]
In my repo I shouldn't have it

**Comment by Zonimi** [comment]
Sorry, but I didn't find anything about igpu because I don't understand how it works, so what should I look for in config.plis?

**Comment by Zonimi** [comment]
Would it be this? https://i.imgur.com/RB2bpFN.jpg

**Comment by Doregon** [comment]
Replace the `PciRoot(0x0),Pci(0x2,0x0)` section with the one from my config.plist. Those framebuffer patches won't work for the i7-8550U.

**Comment by Zonimi** [comment]
I made the replacement but still stuck at the same point as previously: https://i.imgur.com/qEJFq02.png

**Comment by Doregon** [comment]
disable (if you have any) voodooi2c.kext and any of its plugins, voodoops2controller.kext and any of its plugins, appleps2smarttouchpad.kext

**Comment by Zonimi** [comment]
I deactivated the voodoo kext, that other kext you mention is not used in EFI, during the boot it stopped at that point: https://i.imgur.com/25OG8gM.png

**Comment by Doregon** [comment]
What Voodoo kexts do you have?

**Comment by Zonimi** [comment]
VoodooI2C, VoodooI2CHID and VoodooPS2Controller
