### ISSUE TITLE
Intel AC-7260 Wifi and Bluetooth not working

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [Doregon/Inspiron-5570-KBR-Hackintosh#3]
Hey, I tested this EFI on Inspiron 5570 i5-8250u, AMD 530 ( 2gb ). Everything worked seamlessly except for the Wifi and Bluetooth even with AirportItlwm configured, any help would be appreciated

**Comment by Doregon** [comment]
big sur or monterey

**Comment by AbdurrehmanSubhani** [comment]
Big Sur Version 11.6.1.

**Comment by Doregon** [comment]
Please see the commit I mentioned this issue in, it should be fixed.

**Comment by AbdurrehmanSubhani** [comment]
Hey, just wanted to let you know I tried the latest big sir EFI but it still had some problems with the Wifi ( connected but showed no internet connection hence wasn't working ) although the bluetooth fix was working just fine. 
I then replaced your AirportItlwm-BigSur kext with the latest release version available on the OpenIntelWireless repo and removed the MaxKernal value after which the Wifi is working perfectly. 
Currently using your EFI with this modification and everything is working great now, thanks for building a great EFI :D
